### ISSUE TITLE
`calendar` starts as an empty array

### ISSUE THREAD

**Issue by jsamr** [its-danny/use-lilius#180]
**Describe the bug**

The current behavior of the `useLililus` hook causes an extraneous commit because `calendar` is set via an effect.

**To Reproduce**

Don't need a reproduction, just look at how calendar is set from an effect:

https://github.com/its-danny/use-lilius/blob/9b776114a25b849744984deb5b0cfb7805b26129/src/use-lilius.ts#L250-L260

**Proposed fix**

Replace `useEffect` with `useMemo` so that `calendar` is immediately available. I'm willing to submit a PR

**Comment by its-danny** [comment]
@jsamr thanks, haven't really done much with `useMemo` but seems like this is the right way to do it. feel free to open a PR and i'll merged it.
