### ISSUE TITLE
Where can I find configuration (Default Component styles) useMultiStyleConfig('Datepicker', {})

### ISSUE THREAD

**Issue by dipenTipstat** [its-danny/use-lilius#269]
**Describe the bug**
styles not applied by Default

**Comment by its-danny** [comment]
@dipenTipstat There aren't any default styles. This library only handles the logic to build a datepicker, but no rendering or anything. The stuff in `examples/` are just examples made with [Chakra](https://chakra-ui.com/). Feel free to copy them but they're not included in the library or anything.
