### ISSUE TITLE
Failed to install using node 16 and 18 (probably > 14)

### ISSUE THREAD

**Issue by eryzriansyah** [its-danny/use-lilius#494]
**Describe the bug**
When using node v14, I could install the package without an error. But I got this error related to husky when I used node v16 and v18.
```
npm ERR! code 1
npm ERR! path C:\...\node_modules\use-lilius
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c C:\Users\SNB_L_~1\AppData\Local\Temp\postinstall-797181eb.cmd
npm ERR! husky - .git can't be found (see https://typicode.github.io/husky/#/?id=custom-directory)
```

**To Reproduce**

- Install node v16 (16.17.0) or v18 (18.15.0)

- Enter `npm i use-lilius` command

**Expected behavior**
Package installed successfully without an error related to husky.

**Comment by its-danny** [comment]
just pushed a new version (2.0.2) that should fix it, I think. i was using the wrong npm hook to setup husky (`postinstall` instead of `prepare`). should be on npm in a few minutes.

**Comment by eryzriansyah** [comment]
Thanks a lot!
